# crime data cleaning
## IMPERFECT FILTERING, MAYBE MISSING DATA IN REPOSITORY BECASUE NUMBERS DONT MATCH UCR, MISSING RAPE DATA...
## EXPORTS ONLY 2018 DATA AT THE MOMENT, IN PREFILTERED FORMATS

library(readr)
library(dplyr)
library(stringr)

crime <- read_csv("../../../Desktop/slmpd_sept13-feb19.csv")

crime <- select(crime, DateOccur, Crime, Description, XCoord, YCoord)
crime <- filter(crime, XCoord != 0 & YCoord != 0)

crime <- mutate(crime, month = lubridate::month(lubridate::mdy_hm(DateOccur)),
                       year = lubridate::year(lubridate::mdy_hm(DateOccur))) %>% select(-DateOccur)

crime <- mutate(crime,
                assault = ifelse(str_detect(Description,"ASS"), TRUE, FALSE),
                robbery = ifelse(str_detect(Description,"ROBBERY"), TRUE, FALSE),
                homicide = ifelse(str_detect(Description,"HOMICIDE"), TRUE, FALSE),
                rape = ifelse(str_detect(Description,"RAPE"), TRUE, FALSE),
                agg = ifelse(str_detect(Description, "AGG"), TRUE, FALSE),
                not_police = ifelse(str_detect(Description, "POL"), FALSE, TRUE),
                agg_assault = ifelse(as.logical(assault * agg * not_police), TRUE, FALSE)
                ) %>%
        select(XCoord, YCoord, month, year, robbery, agg_assault, rape, homicide)

crime <- mutate(crime, filt = ifelse(
  crime$robbery == FALSE & crime$agg_assault == FALSE & crime$rape == FALSE & crime$homicide == FALSE, FALSE, TRUE
))

crime <- filter(crime, filt) %>% select (-filt)

crime_sf <- sf::st_as_sf(crime, coords = c("XCoord", "YCoord"), crs = 102696) %>% sf::st_transform(4326)

# homicide, rape, robbery, assault
# Keep Domestic, Remove Police Officers
"SIMPLE ASSAULT-ADULT/NO INJURY
ASSAULT, ADULT, AGE 17 AND UP-DOMESTIC
ROBBERY-HIGHWAY  /FIREARM USED/SUCCESSFUL
AGG.ASSAULT-FIREARM/CITIZEN ADULT 1ST DEGREE
ROBBERY-HIGHWAY  /STRNGARM/NO INJ/SUCCESS
AGG.ASSAULT-FIREARM/CITIZEN ADULT 3RD DEGREE
AGG.ASSAULT-OTH DANG WEP/CTZEN ADLT 3RD DEGREE
HOMICIDE
AGG.ASSAULT-OTH DANG WEP/CTZEN ADLT 2ND DEGREE  
SIMPLE ASSAULT-CHILD/NO INJURY
ASSLT-AGGRAV-OTH-WPN-3RD-ADULT-DOMESTIC
ASSLT-AGGRAV-FIREARM-3RD-ADULT-DOMESTIC
ASSLT-AGGRAV-OTH-WPN-2ND-ADULT-DOMESTIC
AGG.ASSAULT-KNIFE/CITIZEN ADULT 1ST DEGREE
AGG.ASSAULT-FIREARM/CITIZEN CHILD 1ST DEGREE 
ASSLT-AGGRV-KNIFE/CUT-1ST-ADULT-DOMESTIC 
ASSLT-AGGRV-HND/FST/FT-2ND-ADUL-DOMESTIC 
ROBBERY-RESIDENCE/FIREARM USED/SUCCESSFUL
ROBBERY CARJACKING /FIREARM USED/SUCCESSFUL 
AGG.ASSAULT-HNDS,FST,FEET/CTZEN ADLT 3RD DEGRE 
ASSAULT, CHILD, AGE 16 AND UNDR-DOMESTIC 
ROBBERY-COMMERCE PL/STRNGARM/NO INJ/SUCCESS
ROBBERY-HIGHWAY/OTHR WEPN USED/SUCCESSFUL
AGG.ASSAULT-KNIFE/CITIZEN ADULT 3RD DEGREE 
ASSLT-AGGRAV-FIREARM-1ST-ADULT-DOMESTIC
AGG.ASSAULT-HNDS,FST,FEET/CTZEN ADLT 2ND DEGRE
ASSLT-AGGRV-KNIFE/CUT-3RD-ADULT-DOMESTIC
ROBBERY-HIGHWAY    /KNIFE USED/SUCCESSFUL
ROBBERY-HIGHWAY  /STRNGARM/NO INJ/ATTEMPT 
RAPE -- FORCIBLE
AGG.ASSAULT-OTH DANG WEP/CTZEN ADLT 1ST DEGREE 
ASSLT-AGGRV-HND/FST/FT-3RD-ADUL-DOMESTIC  
AGG.ASSAULT-OTH DANG WEP/CTZEN CHLD 3RD DEGREE 
AGG.ASSAULT-FIREARM/CITIZEN CHILD 3RD DEGREE 
AGG.ASSAULT-FIREARM/CITIZEN ADULT 2ND DEGREE
ASSLT-AGGRV-KNIFE/CUT-2ND-ADULT-DOMESTIC
ASSLT-AGGRAV-OTH-WPN-1ST-ADULT-DOMESTIC
ASSLT-AGGRAV-OTH-WPN-3RD-CHILD-DOMESTIC
AGG.ASSAULT-FIREARM/POLC.OFFICER  3RD DEGREE
ROBBERY-CONVEN STOR/FIREARM USED/SUCCESS 
ROBBERY-HIGHWAY  /STRNGARM/INJURY/SUCCESS
AGG.ASSAULT-OTH DANG WEP/POL OFFC 3RD DEGREE
ROBBERY-GAS STA/FIREARM USED/SUCCESSFUL
ASSLT-AGGRAV-OTH-WPN-2ND-CHILD-DOMESTIC
AGG.ASSAULT-KNIFE/CITIZEN ADULT 2ND DEGREE
ROBBERY-COMMERCE PL/FIREARM USED/ATTEMPT 
ASSLT-AGGRAV-FIREARM-2ND-ADULT-DOMESTIC 
AGG.ASSAULT-OTH DANG WEP/CTZEN CHLD 2ND DEGREE
AGG.ASSAULT-FIREARM/POLC.OFFICER  1ST DEGREE
ROBBERY-RESIDENCE   /FIREARM USED/ATTEMPT
AGG.ASSAULT-OTH DANG WEP/POL OFFC 1ST DEGREE  
ROBBERY-COMMERCE PL/KNIFE USED/SUCCESS 
ROBBERY-CONVEN STOR/STRNGARM/NO INJ/SUCCESS
ROBBERY-HIGHWAY       /KNIFE USED/ATTEMPT
ROBBERY-COMMERCE PL/OTHR WEP USED/SUCCESS
AGG.ASSAULT-OTH DANG WEP/POL OFFC 2ND DEGREE  
ROBBERY CARJACKING /STRNGARM/NO INJ/SUCCESSFUL
AGG.ASSAULT-HNDS,FST,FEET/CTZEN CHLD 3RD DEGRE
ROBBERY-BANK     /FIREARM USED/SUCCESSFUL
ROBBERY-HIGHWAY   /OTHR WEPN USED/ATTEMPT 
ROBBERY-RESIDENCE  /KNIFE USED/SUCCESSFUL
AGG.ASSAULT-HNDS,FST,FEET/CTZEN CHLD 2ND DEGRE
ASLT-AGGRV-HND/FST/FT-2ND-CHILD-DOMESTIC  
ROBBERY CARJACKING /FIREARM USED/ATTEMPT
ROBBERY-MISC/FIREARM USED/SUCCESSFUL
ROBBERY-RESIDENCE /OTHR WEPN USED/SUCCESS
ROBBERY-BANK/STRNGARM/NO INJ/SUCCESS 
ROBBERY-GAS STA/FIREARM USED/ATTEMPT
ASSLT-AGGRAV-FIREARM-1ST-CHILD-DOMESTIC
ROBBERY-HIGHWAY  /STRNGARM/INJURY/ATTEMPT
AGG.ASSAULT-OTH DANG WEP/CTZEN CHLD 1ST DEGREE 
ASLT-AGGRV-HND/FST/FT-1ST-CHILD-DOMESTIC
ASLT-AGGRV-HND/FST/FT-3RD-CHILD-DOMESTIC
AGG.ASSAULT-KNIFE/POLICE OFFICER 3RD DEGREE 
ROBBERY CARJACKING /OTHR WEPN USED/SUCCESSFUL
ASSLT-AGGRAV-OTH-WPN-1ST-CHILD-DOMESTIC 
ASSLT-AGGRV-HND/FST/FT-1ST-ADUL-DOMESTIC 
ROBBERY-GAS STA/STRNGARM/NO INJ/SUCCESS
AGG.ASSAULT-HNDS,FST,FEET/CTZEN CHLD 1ST DEGRE
ASSLT-AGGRAV-FIREARM-3RD-CHILD-DOMESTIC
AGG.ASSAULT-HNDS,FST,FEET/CTZEN ADLT 1ST DEGRE
AGG.ASSAULT-KNIFE/CITIZEN CHILD 3RD DEGREE
ROBBERY-CONVEN STOR/FIREARM USED/ATTEMPT
ROBBERY-CONVEN STOR/OTHR WEP USED/SUCCESS 
ROBBERY-COMMERCE PL/KNIFE USED/ATTEMPT
AGG.ASSAULT-FIREARM/CITIZEN CHILD 2ND DEGREE 
AGG.ASSAULT-KNIFE/CITIZEN CHILD 1ST DEGREE 
ROBBERY-MISC/STRNGARM/NO INJ/SUCCESSFUL
ROBBERY-COMMERCE PL/STRNGARM/INJURY/SUCCESS  
ROBBERY-RESIDENCE/STRNGARM/INJURY/SUCCESS 
ROBBERY-RESIDENCE/STRNGARM/NO INJ/ATTEMPT
ROBBERY CARJACKING /STRNGARM/NO INJ/ATTEMPT 
SEX OFFNS-STATUATORY RAPE/FIRST
ASSLT-AGGRV-KNIFE/CUT-3RD-CHILD-DOMESTIC
ASSLT-AGGRV-KNIFE/CUT-1ST-CHILD-DOMESTIC
RAPE-ATTEMPT FORCIBLE RAPE/FORCIBLE INCEST
ROBBERY-CONVEN STOR/STRNGARM/NO INJ/ATTEMPT 
ROBBERY-BANK        /FIREARM USED/ATTEMPT  
ROBBERY-CONVEN STOR/KNIFE USED/SUCCESS 
ROBBERY-GAS STA/OTHR WEP USED/SUCCESSFUL
ROBBERY-RESIDENCE     /KNIFE USED/ATTEMPT 
ROBBERY CARJACKING /KNIFE USED/SUCCESSFUL
SEX OFFNS-CHILD MOLESTATION-SECOND DEGREE
AGG.ASSAULT-HNDS,FST,FEET/POL OFFC 3RD DEGREE 
AGG.ASSAULT-KNIFE/CITIZEN CHILD 2ND DEGREE
ASSLT-AGGRV-KNIFE/CUT-2ND-CHILD-DOMESTIC 
ROBBERY-BANK   /OTHR WEPN USED/SUCCESSFUL 
ROBBERY-BANK/STRNGARM/NO INJ/ATTEMPT 
ROBBERY-GAS STA/KNIFE USED/SUCCESSFUL      ROBBERY-RESIDENCE /OTHR WEPN USED/ATTEMPT    ROBBERY CARJACKING /STRNGARM/INJURY/SUCCESS
SEX OFFNS-STATUATORY RAPE/SECOND   AGG.ASSAULT-FIREARM/POLC.OFFICER  2ND DEGREE   AGG.ASSAULT-FIREARM/PUBL.OFFICIAL 1ST DEGREE 
AGG.ASSAULT-FIREARM/PUBL.OFFICIAL 3RD DEGREE    AGG.ASSAULT-KNIFE/POLICE OFFICER 1ST DEGREE

ASSLT-AGGRAV-FIREARM-2ND-CHILD-DOMESTIC
ROBBERY-MISC/FIREARM USED/ATTEMPT     ROBBERY CARJACKING /OTHR WEPN USED/ATTEMPT 
AGG.ASSAULT-KNIFE/PUBLIC OFFICIAL 1ST DEGREE
ASLT-AGGRV-HND/FST/FT-2ND-PUB-O-DOMESTIC         ASSLT-AGGRAV-OTH-WPN-1ST-OFCR-DOMESTIC 
ASSLT-AGGRV-OTH-WPN-1ST-PUB-OFC-DOMESTIC       ASSLT-AGGRV-OTH-WPN-2ND-PUB-OFC-DOMESTIC
ROBBERY-BANK          /KNIFE USED/ATTEMPT         ROBBERY-CONVEN STOR/KNIFE USED/ATTEMPT 
ROBBERY-CONVEN STOR/OTHR WEP USED/ATTEMPT             ROBBERY-GAS STA/KNIFE USED/ATTEMPT          ROBBERY-GAS STA/OTHR WEP USED/ATTEMPT 
ROBBERY-GAS STA/STRNGARM/INJURY/SUCCESS        ROBBERY-GAS STA/STRNGARM/NO INJ/ATTEMPT                ROBBERY-MISC/KNIFE USED/ATTEMPT 
ROBBERY-MISC/STRNGARM/INJURY/SUCCESSFUL      ROBBERY-RESIDENCE/STRNGARM/INJURY/ATTEMPT         ROBBERY CARJACKING /KNIFE USED/ATTEMPT 
SEX OFFNS-SX ABUSE/2ND/VIC 12-13 OR INCAPACITA
SIMPLE ASSAULT-PUBLIC OFFICIAL/NO INJURY"


rape <- filter(crime_sf, rape) %>% filter(year == 2018) %>% select(month)
homicide <- filter(crime_sf, homicide) %>% filter(year == 2018) %>% select(month)
rob <- filter(crime_sf, robbery) %>% filter(year == 2018) %>% select(month)
assault <- filter(crime_sf, agg_assault) %>% filter(year == 2018) %>% select(month)







save(rape, homicide, rob, assault, file = "dashboard/crime.rda")