version: '3.3'
services:
    caddy:
        container_name: caddy-server
        image: caddy:2.0.0-alpine
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_data:/data
    crime-dashboard:
        container_name: crime-dashboard
        image: bransonf/stlcrime:latest
        restart: always
        ports:
            - 3838:3838
        depends_on: 
            - caddy
