# Create copy for dashboard

cardiff <- HTML("<p class='sans'> The U.S. Department of Justice found that more than half of violent crime in the United States goes unreported to law enforcement. This is a clear limitation to understanding where violence occurs. The Cardiff Model combines police and hospital data on violence. As a result, key stakeholders from policy makers to public health experts can more accurately assess violence in the community. <a href='https://www.cdc.gov/violenceprevention/publichealthissue/fundedprograms/cardiffmodel/whatis.html', target ='_blank'>Read More at the CDC</a></p>")
about <- HTML("<p class = 'sans'> This project is supported by several important stakeholders in the region. The majority of work was conducted at The Institute for Public Health at Washington University in Saint Louis. <a href ='https://chris-prener.github.io', target ='_blank'>Christopher Prener</a> of Saint Louis University contributed significantly in the access and cleaning of crime data with his R package <a href='https://slu-opengis.github.io/compstatr/', target ='_blank'>compstatr</a>. We would like to thank the Regional Data Alliance as well, for their support in funding the hosting of this dashboard, as well as Jonathan Leek for his work in producing an aggregated dataset of vacancy in St. Louis. For long term support of this dashboard, to notify of issues or to ask further about methodology or development, please contact <a href='mailto:bransonf@wustl.edu'>Branson Fox</a><center><img src='images/IPH.png', width = '300px'><img src='images/RDA.png', width = '300px'></center>")
methods <- HTML("<p class='sans'>Currently, Demographic data comes from the 2017 American Community Survey 5 Year estimates (2013-2017 ACS5). Poverty was calculated as number of individuals living below the 2017 poverty line out of poverty calculable population. Educational Attainment was calculated for the population above the age of 18. Unemployment rate was calculated as number of individuals reporting unemployment out of total individuals reporting currently being in the workforce. Home ownership was calculated as number of individuals reporting ownership of the home they occupy out of total number of homes.</p>
                <p class='sans'>Crime data comes from the City of Saint Louis and is only representative of 2018-May 2019 in this demo. There were no cases of rape in the crime data for 2018. Assaults excluded those against police. Reports are generated from these data. Homicides are assumed to have always involved a firearm.</p>
                <p class='sans'>Environmental data for schools, parks and bus stops were provided by the City of Saint Louis. Other environmental data were scraped from various web sources.</p>
                <p class='sans'>Choropleth maps use Natural Jenks 5 class Breaks.</p>
                <p class='sans'>Weed & Seed Income from guidestar.org and Project Safe Neighborhood spending from usaspending.gov</p>")
nav <- HTML("<p class='sans'>Begin by selecting data and click update when you're ready. You can zoom in the map using the buttons in the top left or by scrolling. You can view the map fullscreen by clicking the square button in the upper left of the map.</p>")
# https://www.tiki-toki.com/timeline/entry/1015170/Gun-Violence-Initiative-St.-Louis-MO/
vp_orgs <- HTML("<h3 id='wns'>Weed & Seed</h3>
                <p class='sans'>Weed & Seed was a federally funded crime prevention inititative which encouraged a two-pronged approach:'weeding' - an increased policing effort, and 'seeding' - an increased community development investment.  The initial evaluations highlighted the lack of prosecution as weak link in the program's success, noting that increasing funding for police activities without also increasing funding for prosecution is non-sustainable and reduces long term impact effectiveness. <a href = 'https://www.ncjrs.gov/pdffiles1/176358.pdf', target ='_blank'>Read More</a></p>

                <h3 id='gbb'>Gun Buyback Program</h3>
                <p class='sans'>Primarily a symbolic intervention.  Staged by police forces, gun buyback programs are meant to encourage members of a community - particularly youth - to hand in illicit firearms in return for money.  SLMPD hold them periodically.</p>

                <h3 id='sas'>Search and Seize</h3>
                <p class='sans'>Search and seize was a collaboration between police and community members to search homes where juvenilles were suspected to be hiding guns. The program occured in three main stages. <a href='https://www.ncjrs.gov/pdffiles1/nij/191332.pdf', target ='_blank'>Read More</a></p>

                <h3 id='saf'>Safe Futures</h3>
                <p class='sans'>The St. Louis SafeFutures program operated under the direction of the Office of Youth Development within the Mayor’s Office. Targeted youth included residents of Enterprise Community neighborhoods located near the business district and those under the supervision of the Juvenile Court. Critical goals of the St. Louis program included guidance and support for at-risk youth, delinquency prevention, promotion of gang-free schools, and expansion of services and programs offered by the Juvenile Court and Department of Youth Services. To meet these goals, St. Louis undertook a variety of activities, including family support, tutoring, job skill training, employment programs, outreach programs, expanded case management services, and the development of a community-wide gang task force. <a href='https://www.ncjrs.gov/pdffiles1/ojjdp/183841.pdf', target ='_blank'>Read More</a></p>


                <h3 id='cfi'>Ceasefire Initiative</h3>
                <p class='sans'>Based off successful results in other major issues struggling against violent crime, a number of organizations and individuals in St. Louis began participating on a Ceasefire Task Force. <a href='https://www.ncjrs.gov/pdffiles1/nij/188741.pdf', target ='_blank'>Read More</a></p>

                <h3 id='sac'>Strategic Approaches to Community Safety Initiative</h3>
                <p class='sans'>SACSI began in St. Louis in October, 2000.  St. Louis was part of the second group of five cities chosen to participate.  SACSI benefited from existing structures and relationships developed by the Ceasefire group, which had begun meeting in 1996. SACSI focused on three distinct program initiatives:</br>1) A spatially focused police effort, which came to be known as the 5th District Initiative. This was later described by program evaluators as the most important of the three SACSI initiatives.</br>2) An emergency-department-based hospital violence intervention program - the first Trauma Intervention Program effort in St. Louis.</br>3) The creation of a most violent offender program focused on law-enforcement identified individuals with substantial criminal records. This came to be known as the Worst of the Worst initiative, and was based on evidence that a small handful of repeat offenders were responsible for a majority of the city's violent crime. <a href='https://www.ncjrs.gov/pdffiles1/nij/grants/210361.pdf', target ='_blank'>Read More</a></p>

                <h3 id='fdi'>5th District Initiative</h3>
                <p class='sans'>Considered one of the most important initiatives piloted in SACSI, the 5th District Initiative began the third week of January 2001 and focused on roughly four square miles housing 28,000 residents.  GOAL: to provide visible suppression of criminal conduct, rapid prosecution and support to high-risk and high-crime communities. The 5th District in St. Louis at this time accounted for a large percentage of the city's violent crime - nearly doubling the average rate in the city and 11x the national average. Notably, by 2002, homicides in the 5th District had fallen to 17, and by April 10, 2003 (when the evaluation of SACSI was submitted) there had been NO homicides reported in the district. In essence, the activities of the 5th District Initiative were an increased police presence and manpower in the area, and an emphasis on coordination between police efforts and prosecution teams. </p>

                <h3 id='psn'>Project Safe Neighborhoods</h3>
                <p class='sans'>Following 9/11, President Bush and Congress directed a large amount of federal funding towards Justice Department initiatives to reduce crime.  Project Safe Neighborhoods was one of these large initiatives, and focused on fostering collaborative crime prevention efforts based on the Boston Ceasefire model and led by the locally based US Attorney's Offices. <a href='https://georgewbush-whitehouse.archives.gov/news/releases/2001/05/20010514-1.html', target ='_blank'>Read More</a></p>

                <h3 id='hbt'>Hospital Based Trauma Intervention</h3>
                <p class='sans'>The initial effort involved cross-training police and hospital trauma personnel, improving the chain of evidence for bullets and other possessions, fostering improved communication, trust and reporting between hospital and police personnel, and in-house intervention counseling for victims of violence. While short lived, this program did have some good outcomes. For example, evaluation of procedures evidenced a need to increase collaboration for accurate reporting of potential crimes: in one report from 2001 it was found that, while 214 gunshot assaults had been reported to police, there were another 43 on record at Barnes Jewish that did not appear in police files. This effort also increased training and procedures for communication between police and hospital staff, and improved the documentation procedures for evidence such as victim belongings or extracted bullets. Like many other St. Louis crime prevention efforts, this one was largely driven by specific, focused, and dedicated leadership at the hospital's trauma center. When that person left to take a job out of state, the effort stalled. One should note, however, that the St. Louis region is currently seeing a revival of this type of intervention, as several regional hospitals and universities have partnered to form a new hospital based trauma intervention program, aimed at interrupting the cycle of violence and providing victim support right at the moment of a violent experience.</p>

                <h3 id='mvo'>Most Violent Offenders</h3>
                <p class='sans'>Also known as the Worst of the Worst (WoW) program.  This effort was notable in that it required a great deal of information sharing and jurisdictional coordination, including efforts from local police departments, prosecutors, Alcohol, Tobacco and Firearms, the juvenile court system and Probation and Parole. The Most Violent Offenders program was prompted by data that suggested a small number of offenders are disproportionately engaged in a large percentage of crimes, and that by pursuing these individuals more directly with a coordinated effort, a reduction in crime could be achieved. Individuals nominated into the initiative by law enforcement would be aggressively pursued for warrants, violation of probation or parole status, or other violations of the law. In December of 2001, the first list of about 10 individuals was identified, based on nominations from the districts to the captain of the Crimes Against Persons Unit.</p>

                <h3 id='wgf'>Wells Goodfellow Neighborhood Initiative</h3>
                <p class='sans'>A police and community driven initiative to extend the policies and policing strategies developed during PSN specifically within the Wells-Goodfellow neighborhood in the City of St. Louis.  This was a police and community driven initiative to extend the policies and policing strategies developed during PSN. Federally funded, and carefully set up to have a strong program evaluation component. Committed working group members included the SLMPD, the Federal Bureau of Alcohol, Tobacco and Firearms, the MO Dept. of Corrections Division of Probation and Parole, the Wells-Goodfellow Alderman representative, and the Mayor's office. <a href='https://journals.sagepub.com/doi/pdf/10.1177/1098611115608506', target ='_blank'>Read More</a></p>

                <h3 id='bha'>Brady Handgun Violence Prevention Act</h3>
                <p class='sans'>The Brady Handgun Violence Prevention Act mandated background checks for handgun purchases and transfers. <a href='https://www.nytimes.com/1991/03/29/opinion/why-i-m-for-the-brady-bill.html', target ='_blank'>Read More</a></p>
                ")

rep_info <- HTML('<h4>About the Data:</h4><p>These reports are generated using data from the City of Saint Louis Metropolitan Police department. Unlike the UCR reports which display all crimes recorded in a month, these reports reflect only incidents that occured in a given month. Notably, counts of rape will usually differ from UCR reports. For crimes that do not contain precise address data, they are excluded from heatmaps and point maps. Counts on maps may not always reflect counts in tables due to missing information as well.</p>')

save(cardiff, about, methods, vp_orgs, nav, rep_info, file = "../dashboard/dashboard/copy.rda")